name: "PR Title Checker"
description: "Checks if the PR Title follows contribution guidelines."
branding:
  icon: "tag"
  color: "purple"
on: [pull_request]
inputs:
  GITHUB_TOKEN:
    required: false
  pass_on_octokit_error:
    description: "force CI to pass if an octokit error (e.g. missing GITHUB_TOKEN) occurs"
    default: false
  configuration_path:
    description: "config file path"
    default: ".github/pr-title-checker-config.json"
  message:
    required: false
    description: "create a comment message"
runs:
  using: "node12"
  main: "dist/index.js"
